### ISSUE TITLE
Lab 2 Cannot create Tweet.csv

### ISSUE THREAD

**Issue by samc99** [jakobzhao/geog458#12]
Hello all, 

I am late on assignments, but I just want some enlightenment on how the **Jupyter** notebook, .**ipynb files**, and **GitHub** work altogether. 

When we click[ Launch Binder](https://mybinder.org/v2/gh/jakobzhao/geog458.git/master) from Lab 2, why do I see the same GitHub classroom structures in the file? Does it open Bo's version of the notebook? 

When I enter the customer key and secret as well as tokens and run on the code, it does not create a tweet.csv file. 

I know I am a noob in computers, but I just want some patient master at this kind of things to teach me. Thanks ahead.

**Comment by jouho** [comment]
>I just want some enlightenment on how the Jupyter notebook, .ipynb files, and GitHub work altogether.

\- You can simply think of Jupyter notebook as a Python IDE (integrated development environment) that runs on your web browser. You can write code, edit code, and execute it. .ipynb is a file format that stores all the data that you write on Jupyter notebook. GitHub is an opensource repository hosting service that we can all access. In lab2 specifically, we use GitHub to access the code we are using. Binder lets run Jupyter on a server so that we can run python code shared on GitHub without having to worry about system configuration. 

>When we click Launch Binder from Lab 2, why do I see the same GitHub classroom structures in the file? Does it open Bo's version of the notebook?

\- It opens Jupyter with all the files currently stored in this `geog458` repository. All of us have access to the exact same files when you launch it. In lab2, you are supposed to navigate to the `lab2` file and work with the code.

>When I enter the customer key and secret as well as tokens and run on the code, it does not create a tweet.csv file.

\- Could you attach images of your code and error message if there is any?  Make sure to blur out your API keys for security purposes.

**Comment by Sindhooja-Mullapudi** [comment]
If the code isn't creating any changes in the tweet.csv file, try completely clearing the kernel and its output and then re-running it. I had the same issue, but clearing and running fixed it!
