### ISSUE TITLE
Lab4: Map doesn't show on the link

### ISSUE THREAD

**Issue by yi-hsuankao** [jakobzhao/geog458#20]
I uploaded my HTML file on GitHub. When I click on the URL, it showed me a blank page without my map. However, when I used Preview HTML on Atom, the map did show on the page. I am wondering how can I fix the problem?

**Comment by kiku511** [comment]
Hi Amanda! I just checked out the console on your website, I think the problem is that you are trying to load some of your scripts and stylesheets using http instead of https. Because of that the browser gets confused whether the website should be http or https and does not render. 

https://github.com/amandakaoo/olympic-cities/blob/d1055ba0d76e90112cee259e32512fc9c33f2e70/index.html#L31-L33

Try making these https and then check it out once

**Comment by kiku511** [comment]
Also, if you get an error that the url for leaflet is not found on https, check out these links on this webpage <https://cdnjs.com/libraries/leaflet> . I think you should be able to see your map then.

**Comment by yi-hsuankao** [comment]
Thank you so much! It works now.

**Comment by angellinn** [comment]
Hi @kiku511, I've encountered the same problem but after fixing the https, my map still doesn't show. Would you mind taking a look at my code? Thank you so much!

https://github.com/angellinn/tile-taipei

**Comment by kiku511** [comment]
Hi @angellinn, I just checked out your repository and found a potential cause. If you go to the browser console on your [angellinn.github.io/tile-taipei](https://angellinn.github.io/tile-taipei/), you will find your errors in the console. You have a couple of http URLs mixed with the https URLs. I would suggest making all of them https.

**Comment by angellinn** [comment]
Hi @kiku511 thank you for helping out! I also noticed that there's some problem with my source for Leaflet. The map shows after changing it to <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"></script>. Thanks again!

**Comment by jakobzhao** [comment]
thanks @kiku511
